language: php

php:
  - '7.3'
  - nightly

before_install:
    - travis_retry composer self-update

install:
  - composer install

script:
  - composer test

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
